repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: d8a44784fcf4920ac11d10b9c12549a6f73de67a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
        - -v
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: flake8
        args:
        - --max-line-length=100
-   repo: https://github.com/FalconSocial/pre-commit-python-sorter
    rev: b7f5d468c67c3c4a6ea7cdf68c40778095b0f19b
    hooks:
    -   id: python-import-sorter
        args:
        - --silent-overwrite
-   repo: https://github.com/guykisel/prospector-mirror
    rev: 7ff847e779347033ebbd9e3b88279e7f3a998b45
    hooks:
    -   id: prospector
        args:
        - -o=pylint
        - --strictness=verylow
